version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: harbor.apps.prod.vodafoneidea.in/devops/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus

    environment:
      - TZ=Asia/Kolkata

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 8443:9090
    networks:
      - monitor-net
   # network_mode: "host"
    labels:
      org.label-schema.group: "monitoring"


  nodeexporter:
    image: harbor.apps.prod.vodafoneidea.in/devops/prom/node-exporter:2.3.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    environment:
      - TZ=Asia/Kolkata

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - monitor-net
   # network_mode: "host"
    labels:
      org.label-schema.group: "monitoring"


  grafana:
    image: harbor.apps.prod.vodafoneidea.in/devops/grafana:8.5.11
    container_name: grafana
   # volumes:
      #- grafana_data:/var/lib/grafana
      #- ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=6dadmin6dadmin
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=Asia/Kolkata
    restart: unless-stopped
    ports:
      - 6443:3000
    networks:
      - monitor-net
   # network_mode: "host"
    labels:
      org.label-schema.group: "monitoring"
